### ISSUE TITLE
Support for other IDEA software

### ISSUE THREAD

**Issue by dustingraham** [tangzx/IntelliJ-Lua#7]
Hi,

If you don't plan to support this, that's fine you can close this. I think this is a cool plugin. But, it won't run on phpstorm. (A friend told me it won't work on webstorm either.)

```
PhpStorm 2016.3.3
Build #PS-163.13906.21, built on March 8, 2017
Licensed to AJA Video Systems / Dustin Graham
You have a perpetual fallback license for this version
Subscription is active until January 3, 2018
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

I don't see any errors in my event log. But, it just simply doesn't do anything. No highlight support, no file support.

Hope you'll consider supporting this. But if not, I understand.

Thanks,
-Dustin

**Comment by JoBoDo** [comment]
WebStorm 2016.3.1
Build #WS-163.7743.51, built on November 23, 2016
Licensed to Joshua McManus
Subscription is active until September 19, 2017
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

Just as an addition to this note, I'm the friend Dustin referred to. Would really love it if this could work it looks like a great plugin.

谢谢

**Comment by tangzx** [comment]
HI JoBoDo & Dustin, yes it shoud support every software which based on IDEA,  released new version `1.0.5` just now, try [this](https://github.com/tangzx/IntelliJ-Lua/releases/tag/1.0.5)
不客气

**Comment by dustingraham** [comment]
1.0.5 Appears to be working for me. =)

![screenshot from 2017-03-17 09-42-33](https://cloud.githubusercontent.com/assets/1414400/24053689/17058064-0af7-11e7-9351-aaeb1a941471.png)

**Comment by tangzx** [comment]
that's great, enjoy your coding :smile:

**Comment by JoBoDo** [comment]
Yep that fixed it thanks so much!
